services:
  web:
    build: .
    # command: gunicorn nerpa.wsgi:application --bind 0.0.0.0:8000 # ПОПРОБЫВАТЬ УБРАТЬ ДУБЛИКАТ КОМАНДЫ ЗДЕСЬ
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      # - media_volume:/app/media # Отключаем медиафайлы
    expose:
      - 8000
    env_file:
      - .env # Рекомендуется хранить переменные окружения в .env файле

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf # Конфиг nginx
      - static_volume:/app/staticfiles
      # - media_volume:/app/media # Отключаем медиафайлы
    depends_on:
      - web

volumes:
  static_volume:
  # media_volume: # Отключаем хранилище медиафайлы